CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y

CONFIG_I2S=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_LOG=y

CONFIG_SD_RETRY_COUNT=20
CONFIG_SD_CMD_RETRIES=3
CONFIG_SD_INIT_TIMEOUT=3000
CONFIG_SD_CMD_TIMEOUT=500

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_HEAP_MEM_POOL_SIZE=16384
